### ISSUE TITLE
Narrow screen

### ISSUE THREAD

**Issue by maeyler** [a0m0rajab/BahisQurani#10]
The display mode should be optimized for screen width about 450px

Your work will be used primarily in mobile devices 

During the development, Dev Tools will take most of the screen width

**Comment by a0m0rajab** [comment]
Gonna check it after finishing the Docs and pagination.
________________________________

**Comment by maeyler** [comment]
Context menu is off-screen

![image](https://user-images.githubusercontent.com/14038292/75646002-2fae0580-5c59-11ea-94be-928daa3c1f06.png)

**Comment by a0m0rajab** [comment]
Fixed!
you can check the dev version, if it's fine i will merge it. 
https://a0m0rajab.github.io/BahisQuraniDev/finder#b=bsm%20Allh

**Comment by maeyler** [comment]
That particular problem seems OK -- there are others:

* *Modify Version* as soon as you change anything

* *Remove *the following from console output: MouseEvent, togglehide,
hashChanged...

* Check for *empty string* before searching

[image: image.png]

**Comment by maeyler** [comment]
![image](https://user-images.githubusercontent.com/14038292/75852580-5c9b1d80-5dfd-11ea-82e1-fddb4dd558e2.png)

**Comment by maeyler** [comment]
All problems in this issue are resolved
