### ISSUE TITLE
unreadable links

### ISSUE THREAD

**Issue by a0m0rajab** [a0m0rajab/BahisQurani#4]
Having the finder links as this way would make it awful for future use. @maeyler

https://a0m0rajab.github.io/BahisQurani/finder#w=%D9%88%D9%8E%D9%85%D9%8E%D8%A7%20%D8%AA%D9%8E%D9%88%D9%92%D9%81%D9%90%D9%8A%D9%82%D9%90%D9%89%D9%93%20%D8%A5%D9%90%D9%84%D9%91%D9%8E%D8%A7%20%D8%A8%D9%90%D9%B1%D9%84%D9%84%D9%91%D9%8E%D9%87%D9%90  
 
I tried to use buckwalter before yet it get broken during turkish/english search, will have to find a solution maybe by using a flag to check if bukwalter or english/turkish

**Comment by maeyler** [comment]
Arapça aramak için
w="وَيْلَكُمْ"  ya da
b="wayolakumo"

Tercümede aramak için
w="size yazık"  ya da
t="size yazık"

Şimdiki duruma 'b' eklesen yeterli olur
't' benim için gerekli değil

**Comment by maeyler** [comment]
To search in Arabic:
w=وَيْلَكُمْ  or  b=wayolakumo

To search in Translation:
w=size%20yazık  or  t=size%20yazık

**Comment by a0m0rajab** [comment]
Done
